### ISSUE TITLE
Guidelines for milestone 1

### ISSUE THREAD

**Issue by iris0614** [UBC-MDS/DSCI-532_2024_5_HomeScope#2]
### Write descriptive, brief commit messages that explain the purpose of the commit.
- Commit messages should be capitalized and complete the sentence "This commit will..."
- **Good examples**: "Make the readme more welcoming", "Refactor optional import logic", "Enable PPI setting on PNG CLI export"
- Bad examples: "added notebook", "Update analysis", "Fixes", "I hope this works", "asdfsdfasdf" (we've all been there)

**In conclusion, ensure our commit messages are descriptive, not only for normal commits but also for 'squash and merge' actions.**

### Git push and merge rules
- Each PR should contain one main feature/fix (possibly consiting of a few tightly connected smaller features/fixes).
- Each PR should have one approving review before being merged.
- Only use ["squash and merge"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits), so that you can keep an easy to read commit history on main while also being able to track details for each commit via the PR link in the commit message.

**In conclusion, once you are certain that this feature(one feature, one branch) is completely stable, you can use 'Squash and Merge.' However, if you are still actively working on the branch, you should avoid selecting 'Squash and Merge' as it will fail to consolidate commits within the same branch.**

- example: https://github.ubc.ca/MDS-2023-24/DSCI_532_milestone1_group05/blob/master/milestone1.md

**Comment by iris0614** [comment]
### submit details:
- must [create a release on GitHub.com](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) before the submission deadline.

**submit two files on gradescope:**
- link-to-release.ipynb: Includes a single markdown cell with the link to your M1 release on GitHub.
- teamwork-contract.md: Your teamwork contract as per the instructions in the section [Teamwork contract](https://github.ubc.ca/MDS-2023-24/DSCI_532_milestone1_group05/blob/master/milestone1.md#3-teamwork-contract) (do not include this file in your GitHub repo as it might contain private information).

**Comment by iris0614** [comment]
#### Cited from Aishwarya Nadimpally
- Below is the general workflow we need to follow for a good project management:
- Clone/pull the latest version from main branch.
- Open your issue on which you are working. In the issue window, you can find an option "create a branch".
- Once the new branch is created you can copy the commands and paste it in your git bash/terminal, so that your local folder will direct to your newly created branch.
- Now you can start working on your assigned task.
- Once you are done with your task. You can do git commit with a meaningful message git commit -m "Updated Readme as per our application requirements"  then do git push
- Now in github page, you can create a pull request and assign at least 2 members for review.
- If you have received any feedback or changes to be done on your work based on the review, then kindly do the changes and commit  and push to the same branch (Here no need to create a new pull request, because your PR is still in open).
Once you got approval from both of the reviewers, then do squash and merge to main branch.
- **Points to be Noted**: Commit messages should be  meaningful. Have some communication on the issues. Move the issues to ToDo,Done in project board.

**Comment by nassimgha** [comment]
Section 3: Research Questions and Usage Scenarios
Persona Description
Name: Jacob Tremblay
Role: Real Estate Analyst at a Canadian Urban Development Firm
Background: Jacob has extensive experience in urban planning and real estate market analysis. His firm is tasked with advising local governments on development policies that align with market trends and housing affordability initiatives.
Goal: To gather insights on the real estate market across Canada's most populous cities to inform development policies and investment strategies.
User Story and Usage Scenario
Jacob logs onto the "Estate_Track" dashboard with the goal of [identifying] market trends and [assessing] the impact of demographic factors on housing prices. He aims to [compare] various housing markets and [extract] actionable data to support urban development plans.
As he navigates the dashboard:
Exploring the Map: Jacob starts by exploring the interactive map, hovering over cities to see a tooltip with the average house price and clicking on cities for more in-depth statistics. This immediate visual assessment helps him [identify] regions with the highest market activity.
Filtering Data: Utilizing the filter panel, he [narrows] down his search to cities with a median family income below a specific threshold, aiming to understand affordability issues. He adjusts sliders for the number of bedrooms and bathrooms to reflect typical family homes.
Analyzing Trends: In the trends section, Jacob examines historical price changes through line charts. He's looking for patterns that show the rate of increase in housing prices, which he [compares] with median income growth rates.
Not sure if we can add this as the data is not current: Viewing Listings: He scrolls through the listings that match his filters, [noting] properties that are outliers in terms of price, which could indicate a potential for market correction or unique investment opportunities.
Taking Action: Based on the dashboard's data, Jacob [concludes] that certain cities show a concerning disparity between income and housing prices. He decides to [recommend] targeted policy interventions in these areas, such as development incentives for affordable housing.
By using the "Estate_Track" dashboard, Jacob is able to [synthesize] comprehensive data into a clear narrative for his firm's consulting services. This leads to data-driven recommendations that can shape future urban development and real estate investment, ensuring that policies are responsive to actual market conditions.

**Comment by nassimgha** [comment]
Thank you Aishwarya for the sketch, how did you make this so fast? impressive! It looks very good. But I think we can make some changes, and I have a few suggestions about the dashboard, I did some readings and research, and here are my ideas:                        Map View is very good,  and we can have interactive markers for each city that show average house prices when hovered over.
Search and Filter Panel:
the panel is very good
do you think we can have a search bar to enter specific addresses or city names?
Data Summary View:
A summary section showing the average, median, and range of property prices across the filtered dataset. I think instead of putting a chart for the population and another one for income, we could make it a comparison to the average house price in the selected city or province.
Detailed Listings View:
A scrollable list or table displaying individual listings that match the filters, showing details like address, price, number of bedrooms and bathrooms, do you think we can do that?
Trends Over Time:
A line chart or bar graph to show trends in housing prices over time for selected cities.
Toggle options to view data by year, quarter, or month.
Comparative Analysis:
Side-by-side comparison of average prices, population, and income for two or more selected cities.

**Comment by iris0614** [comment]
Your points are very good. Let's discuss them in detail during lab time.

**Comment by iris0614** [comment]
- If you need to change the commit message for the latest commit, use 'git commit --amend -m "NEW commit message"'. However, for the previous commit, you should execute 'git reset --soft HEAD~2' (the number depends on the specific commit position).
https://www.atlassian.com/git/tutorials/rewriting-history
