### ISSUE TITLE
Milestone 2--assignment

### ISSUE THREAD

**Issue by iris0614** [UBC-MDS/DSCI-532_2024_5_HomeScope#25]
milestone 2: https://github.ubc.ca/MDS-2023-24/DSCI_532_milestone2_group05/blob/master/milestone2.md
good example: https://github.com/KirstieJane/STEMMRoleModels
color and widget format: https://bootswatch.com/cyborg/

**Comment by Aishwarya120111** [comment]
Below are tasks:
(Feel free to add If I miss anything)

1. Update README file
2. Create Reflection document
3. Development of Dashboard
4. Dashboard Deployment

**Comment by iris0614** [comment]
Milestone2:
Creating the 5 input widgets - Iris
Output 2:Plot the map with province and city details - Aishwarya
Output 1: Creating bar plot and table by combining 4/5 variables - Carrie
Output 3: Creating a plot for price distribution across province - Nasim
Output 4: Creating cards to show the housing statistics - Nasim
Output 5: Creating 2 scatter plot by combining 4/5 variables - Iris
Deployment of App - Aishwarya
Update README as per the guidelines - Iris
Reflection document - All (Write your plots description in this document)
Record the Dashboard App - Aishwarya
Formatting the Dashboard as per the Milestone requirements - Iris
Release - Aishwarya (Before 6 PM Sat)
