### ISSUE TITLE
Add correct deployment URL in "About" section

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_5_HomeScope#54]
@Aishwarya120111 @iris0614 @carrieyanyi @nassimgha I'm reviewing some things regarding the apps that we need for next week. I have noticed that you have added the wrong deployment URL in the "About" section of your repo (yours go to a PR which no longer exists). Could you please add the main app URL there (see the milestone for instructions)?

**Comment by carrieyanyi** [comment]
Hi Joel, Thank you for pointing out this issue. We have fixed it already!
