### ISSUE TITLE
Feedback from Nicole Tu

### ISSUE THREAD

**Issue by Nicole-Tu97** [UBC-MDS/DSCI-532_2024_5_HomeScope#67]
Overall, the dashboard looks pretty good! It excels in providing a rich, interactive user experience with a clean and professional design that facilitates easy navigation through different data insights. The inclusion of a map for geographical visualization is particularly impressive, as it allows users to understand the spatial distribution of property values at a glance. Moreover, the interactive filters are a strong feature that empower users to tailor the data analysis to their specific needs and interests. This level of customization is invaluable for stakeholders looking to make informed decisions. Additionally, the bar plot juxtaposing Price with Median Family Income is an excellent example of comparative analysis, enabling users to quickly assess key market indicators. 
Intuitiveness and User Guidance. 

To make the dashboard even better, here are some aspects that could be improved:

**1. User Guidance:** The dashboard contains a wealth of information, which is great for detailed analysis. However, for new users or those less familiar with data analysis, it may be overwhelming. Including a brief tutorial or guided tour of the dashboard features upon first visit could improve user experience by providing context for what they're viewing and how to interact with the data.

**2. Data Visualization and Accessibility:** The scatter plots (Price-Bedroom Correlation and Price-Bathroom Correlation) have points that are quite dense in some areas. Consider implementing a feature like zooming or hover-over tooltips that display more information about each point. This would allow users to more easily interpret specific data points in crowded plots.

**3. Contrast and Legibility:** The bar plot comparing Price and Median Family Income might benefit from enhanced contrast or a different color scheme. The blue for Price is quite strong compared to the red for Median Family Income, which could make it a bit difficult for users with visual impairments or color blindness to interpret the graph effectively.

**4. Layout and Design:** The layout is quite linear and requires significant scrolling, which might cause users to miss out on important information at the bottom if they don't scroll all the way down. Organizing content into tabs or having a side navigation bar for different sections could streamline the user experience and ensure all information is easily accessible.

**5. Big Picture — Market Dynamics and Predictive Insights:** While the dashboard does an excellent job at presenting current and historical data, it could be enhanced by integrating predictive analytics. Since the target audience includes investors and market analysts, providing forward-looking insights based on market trends could be invaluable. This could include predictive models for price trends or a feature that simulates how changes in market variables might affect property values.

**Comment by carrieyanyi** [comment]
Thank you for reviewing our dashboard and providing solid suggestions.
 
Here are some improvements addressing your comment:
- We include a short demo in our README file to enhance our reader interpretability of the dashboard in general.
- We removed the scatter plots and replaced them with a bar chart with tooltip.
- We have created a color theme for the whole dashboard.
- We adjust the chart size to show at least four graphs in one goal.
- Since our dataset only has 2023 data, at this stage, we can not provide any predictive analysis. We may improve the function in the future as more data has been collected.
