### ISSUE TITLE
Feedback from Dan Zhang

### ISSUE THREAD

**Issue by wqxxzd** [UBC-MDS/DSCI-532_2024_5_HomeScope#73]
The overall view of the dashboard is fantastic. It effectively communicates its intended message, and the information provided is detailed and easy to interpret. However, I have noticed a few small details that could enhance the dashboard even further.

1. If you could locate the GeoJson file, using the Choropleth Maps might be more beneficial than heatmaps. Choropleth Maps would more clearly represent the boundaries for each city, as using a single point can be challenging to discern.
2. Adding a brief description next to the title could help clarify the content, as it is somewhat difficult to understand based solely on the title.
3. Would it be possible to separate these plots with dividers or use the Card component? This might improve the visual organization.
4. I would recommend using a consistent color scale across all plots, if feasible.
5. Could you modify the hover content for the bedroom distribution? The current use of x, y, and text is a bit confusing.

**Comment by carrieyanyi** [comment]
Thank you for reviewing our dashboard and provide suggestion for improvement.
Here are the areas that address your concern:
- We tried to import another dataset, however, it is time-consuming and beyond our capability. But this is a good suggestion, and we will take it into account for future improvement.
- We added a short description below the title to enhance readability.
- We tried to use a divider, but it does not look well on our dashboard. We use similar color on Card to improve the visual organization.
- We applied the same color theme on the dashboard.
- We adjusted the hover content and now it shows the total count.
