### ISSUE TITLE
Feedback from Kiersten Gilberg

### ISSUE THREAD

**Issue by Kierst01** [UBC-MDS/DSCI-532_2024_5_HomeScope#74]
Is the app overall well-suited to the usage scenario and target audience?
- I think this dashboard was well-suited to the usage scenario and target audience. It contains the necessary information for their users (real estate investors, developers, market analysts, or urban planner) to assess the housing investment market.

Do you see some ways that the dashboard could be extended to better cater to the target audience or meet the specifications in the usage scenario?
- I think since one of the metrics used is median family income, it would make more sense to compare this to median price instead of average in the barplot. 
- I thought the price distribution chart and summary statistics were very useful!

Was the app intuitive to use? Did it behave as you expected?
- Overall I think the dashboard was intuitive. However, the first barplot with the two axis may be confusing to the user audience, since it looked like median income was larger than average price at first glance. I think this can be useful for provinces that have more than one city, but less so when there is only one city selected. I would suggest adding more cities to the default value so that it automatically displays with multiple values to compare.
- I also noticed was that when Newfoundland and Labrador is selected the city defaults to Nanaimo, BC, which is what then shows on the map. It seemed to work correctly for other input values.

Can you think of other alternatives or improvements for the plots regarding the selection of the plots or how they are set up to reach to the widgets?
- I think the instructions for selecting the bar chart filters on the left-hand side could be improved. Instead of saying "Bar Plot First Variable", "Bar Plot Second Variable" and "Bar Plot Third Variable" it could say "Bar Plot First Axis Variable", "Bar Plot Second Axis Variable" and "Bottom Bar Plot Variable". Or the dropdown for the bottom plot could be put directly above the chart.

Are the plots or other outputs sufficiently described / intuitive enough for the target audience?
- Yes, I think the titles describe the plots well and are easy to interpret. However, for the price variable of the barplots I think including the summary metric would help with clarity, eg. "Average Price".

Overall, I thought this Dashboard was easy to use with a nice layout. It also matches the intended user audience well, good job!

**Comment by carrieyanyi** [comment]
Thank you for reviewing our dashboard and providing feedback!
Here are some areas that we addressing:
- We adjusted the variable dropdown menus closing to each chart, enhancing reader interpretability. 
- We set the default of two cites per province to show the comparison at the start. 
- We changed the Card title to be more clear and efficient.
